{
 "title": "Kong API Gateway Dashboard",
 "tags": [
  "kong",
  "api-gateway"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kong_http_requests_total[5m])) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "rate(kong_latency_bucket[5m])", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(kong_http_status{code=~\"2.*\"}[5m])) by (service)",
     "legendFormat": "2xx - {{service}}"
    },
    {
     "expr": "sum(rate(kong_http_status{code=~\"4.*\"}[5m])) by (service)",
     "legendFormat": "4xx - {{service}}"
    },
    {
     "expr": "sum(rate(kong_http_status{code=~\"5.*\"}[5m])) by (service)",
     "legendFormat": "5xx - {{service}}"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kong_bandwidth{type=\"egress\"}[5m])) by (service)",
     "legendFormat": "{{service}} - Egress"
    },
    {
     "expr": "sum(rate(kong_bandwidth{type=\"ingress\"}[5m])) by (service)",
     "legendFormat": "{{service}} - Ingress"
    }
   ]
  }
 ]
}